name: rlee
dependencies:
  - pip
  - pip:
    # requirements.txt
    - atari-py==0.1.7
    - ConfigArgParse==0.14.0
    - gym==0.10.9
    - numpy==1.15.4
    - opencv-python==3.4.5.20
    - scipy==1.2.0
    - torch==1.0.0
    - wandb==0.6.32
    # requirements-dev.txt
    - black==18.9b0
    - flake8==3.6.0
    - flake8-bugbear==18.8.0
    - flake8-docstrings==1.3.0
    - isort==4.3.4
    - mypy===0.660
    - pre-commit==1.14.2
    - pycodestyle==2.4.0
    - pydocstyle==3.0.0
    - pyflakes==2.0.0
    - pytest==4.2.0
    - seed-isort-config==1.5.0
